// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from "storyblok";
export interface RichtextStoryblok {
  type: string;
  content?: RichtextStoryblok[];
  marks?: RichtextStoryblok[];
  attrs?: any;
  text?: string;
  [k: string]: any;
}

export interface AppSettingsStoryblok {
  login: LoginInfoStoryblok[];
  signup: SignupInfoStoryblok[];
  contract_terms: RichtextStoryblok;
  antispam_policy: RichtextStoryblok;
  legal?: any;
  component: "app-settings";
  _uid: string;
  [k: string]: any;
}

export interface AutomationExamplesGridStoryblok {
  component: "automation-examples-grid";
  _uid: string;
  [k: string]: any;
}

export interface BentoFourStoryblok {
  items?: BentoItemStoryblok[];
  component: "bento-four";
  _uid: string;
  [k: string]: any;
}

export interface BentoFourMansonryStoryblok {
  items?: BentoItemStoryblok[];
  component: "bento-four-mansonry";
  _uid: string;
  [k: string]: any;
}

export interface AssetStoryblok {
  alt: string | null;
  copyright?: string | null;
  fieldtype: "asset";
  id: number;
  filename: string | null;
  name: string;
  title: string | null;
  focus: string | null;
  meta_data?: {
    [k: string]: any;
  };
  source?: string | null;
  is_external_url?: boolean;
  is_private?: boolean;
  src?: string;
  updated_at?: string;
  width?: number | null;
  height?: number | null;
  aspect_ratio?: number | null;
  public_id?: string | null;
  content_type?: string;
  [k: string]: any;
}

export interface BentoItemStoryblok {
  title?: string;
  subtitle?: RichtextStoryblok;
  image?: AssetStoryblok;
  component: "bento-item";
  _uid: string;
  [k: string]: any;
}

export interface BentoSixStoryblok {
  items?: BentoItemStoryblok[];
  component: "bento-six";
  _uid: string;
  [k: string]: any;
}

export interface BentoSixMansonryStoryblok {
  items?: BentoItemStoryblok[];
  component: "bento-six-mansonry";
  _uid: string;
  [k: string]: any;
}

export interface BentoThreeStoryblok {
  items?: BentoItemStoryblok[];
  component: "bento-three";
  _uid: string;
  [k: string]: any;
}

export interface BlogArticleGridStoryblok {
  component: "blog-article-grid";
  _uid: string;
  [k: string]: any;
}

export interface BlogAuthorStoryblok {
  name?: string;
  avatar?: AssetStoryblok;
  component: "blog-author";
  _uid: string;
  [k: string]: any;
}

export interface BlogCategoryStoryblok {
  name?: string;
  description?: string;
  component: "blog-category";
  _uid: string;
  [k: string]: any;
}

export interface BlogTagStoryblok {
  name?: string;
  component: "blog-tag";
  _uid: string;
  [k: string]: any;
}

export interface BoxAlertStoryblok {
  color: "" | "info" | "warning" | "error" | "success" | "brand" | "neutral";
  content: RichtextStoryblok;
  component: "box-alert";
  _uid: string;
  [k: string]: any;
}

export interface CallToActionStoryblok {
  title: string;
  show_signup?: boolean;
  show_demo?: boolean;
  signup_text?: string;
  component: "call-to-action";
  _uid: string;
  [k: string]: any;
}

export interface CallToActionImageStoryblok {
  title: string;
  signup_text?: string;
  image: AssetStoryblok;
  component: "call-to-action-image";
  _uid: string;
  [k: string]: any;
}

export type MultilinkStoryblok =
  | {
      fieldtype: "multilink";
      id: string;
      url: string;
      cached_url: string;
      target?: "_blank" | "_self";
      anchor?: string;
      rel?: string;
      title?: string;
      prep?: string;
      linktype: "story";
      story?: {
        name: string;
        created_at?: string;
        published_at?: string;
        id: number;
        uuid: string;
        content?: {
          [k: string]: any;
        };
        slug: string;
        full_slug: string;
        sort_by_date?: null | string;
        position?: number;
        tag_list?: string[];
        is_startpage?: boolean;
        parent_id?: null | number;
        meta_data?: null | {
          [k: string]: any;
        };
        group_id?: string;
        first_published_at?: string;
        release_id?: null | number;
        lang?: string;
        path?: null | string;
        alternates?: any[];
        default_full_slug?: null | string;
        translated_slugs?: null | any[];
        [k: string]: any;
      };
      [k: string]: any;
    }
  | {
      fieldtype: "multilink";
      id: string;
      url: string;
      cached_url: string;
      target?: "_blank" | "_self";
      linktype: "url";
      rel?: string;
      title?: string;
      [k: string]: any;
    }
  | {
      fieldtype: "multilink";
      id: string;
      url: string;
      cached_url: string;
      target?: "_blank" | "_self";
      email?: string;
      linktype: "email";
      [k: string]: any;
    }
  | {
      fieldtype: "multilink";
      id: string;
      url: string;
      cached_url: string;
      target?: "_blank" | "_self";
      linktype: "asset";
      [k: string]: any;
    };

export interface CardItemStoryblok {
  image?: AssetStoryblok;
  title?: string;
  subtitle?: RichtextStoryblok;
  show_link?: boolean;
  link_title?: string;
  link?: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "card-item";
  _uid: string;
  [k: string]: any;
}

export interface CardSliderStoryblok {
  items?: CardItemStoryblok[];
  component: "card-slider";
  _uid: string;
  [k: string]: any;
}

export interface CarouselStoryblok {
  items?: CarouselItemStoryblok[];
  transition_duration?: string;
  slide_duration?: string;
  component: "carousel";
  _uid: string;
  [k: string]: any;
}

export interface CarouselItemStoryblok {
  image?: AssetStoryblok;
  icon: number | string;
  title?: string;
  subtitle?: string;
  component: "carousel-item";
  _uid: string;
  [k: string]: any;
}

export interface CheckListStoryblok {
  title: string;
  content?: RichtextStoryblok;
  component: "check-list";
  _uid: string;
  [k: string]: any;
}

export interface ContactPageStoryblok {
  badge_text: string;
  title: string;
  subtitle: RichtextStoryblok;
  form?: FormContactStoryblok[];
  component: "contact-page";
  _uid: string;
  [k: string]: any;
}

export interface ContainerStoryblok {
  type: "" | "full-width" | "boxed" | "boxed_small";
  background?: "" | "transparent" | "white" | "light" | "dark-gradient" | "light-fade-overlay";
  margin_options: "" | "none" | "top" | "bottom" | "top-bottom";
  content?: any[];
  hide_other_languages?: boolean;
  component: "container";
  _uid: string;
  [k: string]: any;
}

export interface ContentAccordeonStoryblok {
  content_style: "" | "content_with_image_left" | "content_with_image_right" | "faqs";
  items?: ContentAccordeonItemStoryblok[];
  component: "content-accordeon";
  _uid: string;
  [k: string]: any;
}

export interface ContentAccordeonItemStoryblok {
  title: string;
  description: RichtextStoryblok;
  image?: AssetStoryblok;
  component: "content-accordeon-item";
  _uid: string;
  [k: string]: any;
}

export interface ContentAutomationExampleStoryblok {
  title: string;
  image: AssetStoryblok;
  content: RichtextStoryblok;
  component: "content-automation-example";
  _uid: string;
  [k: string]: any;
}

export interface ContentBlogArticleStoryblok {
  title: string;
  author: ISbStoryData<BlogAuthorStoryblok> | string;
  tags?: (ISbStoryData<BlogTagStoryblok> | string)[];
  categories: (ISbStoryData<BlogCategoryStoryblok> | string)[];
  reading_time: string;
  include_h3_in_menu?: boolean;
  excerp: string;
  content: RichtextStoryblok;
  grid_image: AssetStoryblok;
  detail_image: AssetStoryblok;
  main_content?: any;
  media_images?: any;
  classification_and_tags?: any;
  seo_and_metadata?: any;
  component: "content-blog-article";
  _uid: string;
  [k: string]: any;
}

export interface ContentButtonStoryblok {
  label?: string;
  link: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  color: "" | "primary" | "secondary" | "neutral" | "success" | "info" | "warning" | "error";
  variant: "" | "solid" | "outline" | "soft" | "subtle" | "ghost" | "link";
  size: "" | "xs" | "sm" | "md" | "lg" | "xl";
  align?: "" | "justify-start" | "justify-center" | "justify-end";
  component: "content-button";
  _uid: string;
  [k: string]: any;
}

export interface ContentGlossaryTermStoryblok {
  term?: string;
  title?: string;
  author?: ISbStoryData<BlogAuthorStoryblok> | string;
  content?: RichtextStoryblok;
  component: "content-glossary-term";
  _uid: string;
  [k: string]: any;
}

export interface ContentGridStoryblok {
  columns: "" | "2_columns" | "3_columns" | "4_columns";
  items: any[];
  component: "content-grid";
  _uid: string;
  [k: string]: any;
}

export interface ContentGridItemStoryblok {
  theme?: "" | "light" | "dark";
  variant: "" | "icon_left_side" | "icon_top_side" | "none";
  icon?: number | string;
  title: string;
  description: RichtextStoryblok;
  component: "content-grid-item";
  _uid: string;
  [k: string]: any;
}

export interface ContentGuideArticleStoryblok {
  title: string;
  category?: string;
  tags?: (ISbStoryData<BlogTagStoryblok> | string)[];
  reading_time: string;
  include_h3_in_menu?: boolean;
  excerp: string;
  content: RichtextStoryblok;
  grid_image: AssetStoryblok;
  detail_image: AssetStoryblok;
  main_content?: any;
  media_images?: any;
  classification_and_tags?: any;
  seo_and_metadata?: any;
  component: "content-guide-article";
  _uid: string;
  [k: string]: any;
}

export interface ContentHeaderStoryblok {
  theme: "" | "light" | "dark";
  show_badge?: boolean;
  badge_text?: string;
  heading: RichtextStoryblok;
  subheading?: RichtextStoryblok;
  component: "content-header";
  _uid: string;
  [k: string]: any;
}

export interface ContentImageStoryblok {
  image?: AssetStoryblok;
  component: "content-image";
  _uid: string;
  [k: string]: any;
}

export interface ContentImageSplitContentStoryblok {
  show_image?: boolean;
  image?: AssetStoryblok;
  left_column?: ContentImageSplitContentColumnStoryblok[];
  right_column?: ContentImageSplitContentColumnStoryblok[];
  component: "content-image-split-content";
  _uid: string;
  [k: string]: any;
}

export interface ContentImageSplitContentColumnStoryblok {
  title?: string;
  content?: string;
  items?: ContentGridItemStoryblok[];
  component: "content-image-split-content-column";
  _uid: string;
  [k: string]: any;
}

export interface ContentIntegrationStoryblok {
  logo?: AssetStoryblok;
  placeholder_logo?: boolean;
  connect?: string;
  title: string;
  developer?: string;
  categories: (ISbStoryData<IntegrationCatgoryStoryblok> | ISbStoryData<IntegrationCategoryStoryblok> | string)[];
  use_cases?: (ISbStoryData<IntegrationUseCaseStoryblok> | string)[];
  min_plan: "" | "FREE" | "starter" | "business" | "premium";
  featured?: boolean;
  related_links?: IntegrationLinkStoryblok[];
  integration_platforms?: IntegrationPlatformStoryblok[];
  excerpt: string;
  content?: RichtextStoryblok;
  component: "content-integration";
  _uid: string;
  [k: string]: any;
}

export interface ContentLandingPageStoryblok {
  text_cta: string;
  body?: ContainerStoryblok[];
  component: "content-landing-page";
  _uid: string;
  [k: string]: any;
}

export interface ContentLegalPageStoryblok {
  title: string;
  content?: RichtextStoryblok;
  component: "content-legal-page";
  _uid: string;
  [k: string]: any;
}

export interface ContentLinkStoryblok {
  title: string;
  link: Exclude<MultilinkStoryblok, {linktype?: "email"}>;
  align?: "" | "left" | "right" | "center";
  component: "content-link";
  _uid: string;
  [k: string]: any;
}

export interface ContentPricingStoryblok {
  component: "content-pricing";
  _uid: string;
  [k: string]: any;
}

export interface ContentResourceStoryblok {
  title: string;
  grid_image?: AssetStoryblok;
  hash?: string;
  category?: string;
  excerp: string;
  body?: ContainerStoryblok[];
  component: "content-resource";
  _uid: string;
  [k: string]: any;
}

export interface ContentRichTextStoryblok {
  content?: RichtextStoryblok;
  component: "content-rich-text";
  _uid: string;
  [k: string]: any;
}

export interface ContentSplitImageStoryblok {
  content_direction: "" | "image_right" | "image_left";
  image: AssetStoryblok;
  section_header: SectionHeaderStoryblok[];
  section_content?: RichtextStoryblok;
  component: "content-split-image";
  _uid: string;
  [k: string]: any;
}

export interface ContentSplitItemsStoryblok {
  section_header: SectionHeaderStoryblok[];
  items?: ContentGridItemStoryblok[];
  component: "content-split-items";
  _uid: string;
  [k: string]: any;
}

export interface ContentStaticPageStoryblok {
  body?: ContainerStoryblok[];
  component: "content-static-page";
  _uid: string;
  [k: string]: any;
}

export interface TableStoryblok {
  thead: {
    _uid: string;
    value?: string;
    component: number;
    [k: string]: any;
  }[];
  tbody: {
    _uid: string;
    body: {
      _uid?: string;
      value?: string;
      component?: number;
      [k: string]: any;
    }[];
    component: number;
    [k: string]: any;
  }[];
  [k: string]: any;
}

export interface ContentTableStoryblok {
  table?: TableStoryblok;
  center?: boolean;
  component: "content-table";
  _uid: string;
  [k: string]: any;
}

export interface ContentTextStoryblok {
  text?: string;
  align?: "" | "text-left" | "text-right" | "text-center";
  size?:
    | ""
    | "text-xs"
    | "text-sm"
    | "text-base"
    | "text-lg"
    | "text-xl"
    | "text-2xl"
    | "text-3xl"
    | "text-4xl"
    | "text-5xl"
    | "text-6xl"
    | "text-7xl";
  font_family?: "" | "font-display" | "font-sans";
  color?: "" | "text-neutral-950" | "text-gray-200" | "text-gray-400" | "text-gray-600" | "text-gray-800";
  font_weight?: "" | "font-normal" | "font-semibold" | "font-bold";
  component: "content-text";
  _uid: string;
  [k: string]: any;
}

export interface ContentVideoStoryblok {
  grid_image?: AssetStoryblok;
  title?: string;
  category?: string;
  url: string;
  time?: string;
  excerpt?: string;
  content?: RichtextStoryblok;
  component: "content-video";
  _uid: string;
  [k: string]: any;
}

export interface ContractTermsStoryblok {
  content: RichtextStoryblok;
  component: "contract-terms";
  _uid: string;
  [k: string]: any;
}

export interface CookieDeclarationStoryblok {
  component: "cookie-declaration";
  _uid: string;
  [k: string]: any;
}

export interface DemoPageStoryblok {
  badge_text: string;
  title: string;
  subtitle: RichtextStoryblok;
  form?: FormDemoStoryblok[];
  component: "demo-page";
  _uid: string;
  [k: string]: any;
}

export interface DividerStoryblok {
  type?: "" | "none" | "line";
  margin:
    | ""
    | "my-1"
    | "my-2"
    | "my-3"
    | "my-5"
    | "my-6"
    | "my-7"
    | "my-8"
    | "my-10"
    | "my-12"
    | "my-14"
    | "my-16"
    | "my-20"
    | "my-24"
    | "my-28"
    | "my-32"
    | "my40"
    | "my-48"
    | "my-56"
    | "my-72";
  component: "divider";
  _uid: string;
  [k: string]: any;
}

export interface EasymailingFormStoryblok {
  hash?: string;
  component: "easymailing-form";
  _uid: string;
  [k: string]: any;
}

export interface EmbedVideoStoryblok {
  url?: string;
  component: "embed-video";
  _uid: string;
  [k: string]: any;
}

export interface ExpertTipStoryblok {
  title: string;
  content?: RichtextStoryblok;
  link?: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  link_text?: string;
  component: "expert-tip";
  _uid: string;
  [k: string]: any;
}

export interface FormContactStoryblok {
  component: "form-contact";
  _uid: string;
  [k: string]: any;
}

export interface FormDemoStoryblok {
  component: "form-demo";
  _uid: string;
  [k: string]: any;
}

export interface FormReportAbuseStoryblok {
  component: "form-report-abuse";
  _uid: string;
  [k: string]: any;
}

export interface GlobalSettingsStoryblok {
  main_menu_items: MainMenuItemStoryblok[];
  footer_social_links?: (SocialLinksStoryblok | SocialIconLinkStoryblok)[];
  footer_menu?: MenuColumnStoryblok[];
  legal_menu?: MenuLinkStoryblok[];
  component: "global-settings";
  _uid: string;
  [k: string]: any;
}

export interface GlossaryTermsGridStoryblok {
  component: "glossary-terms-grid";
  _uid: string;
  [k: string]: any;
}

export interface GuideArticleGridStoryblok {
  component: "guide-article-grid";
  _uid: string;
  [k: string]: any;
}

export interface HeroPageStoryblok {
  badge?: boolean;
  badge_style?: "" | "markee" | "text";
  badge_text?: string;
  show_badge_link?: boolean;
  badge_link?: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  title: string;
  show_divider?: boolean;
  subtitle: RichtextStoryblok;
  show_image?: boolean;
  image?: AssetStoryblok;
  trustpilot?: boolean;
  trustpilot_stars?: string;
  show_register?: boolean;
  display_supporting_text?: boolean;
  supporting_text?: string;
  component: "hero-page";
  _uid: string;
  [k: string]: any;
}

export interface HeroVideoPageStoryblok {
  badge?: boolean;
  badge_style?: "" | "markee" | "text";
  badge_text?: string;
  title: string;
  subtitle: RichtextStoryblok;
  show_divider?: boolean;
  show_register?: boolean;
  supporting_text?: string;
  video_url: string;
  autoplay?: boolean;
  muted?: boolean;
  loop?: boolean;
  controls?: boolean;
  video?: any;
  component: "hero-video-page";
  _uid: string;
  [k: string]: any;
}

export interface ImageBannerStoryblok {
  image?: AssetStoryblok;
  title: string;
  content?: RichtextStoryblok;
  link?: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  link_text?: string;
  component: "image-banner";
  _uid: string;
  [k: string]: any;
}

export interface IntegrationCategoryStoryblok {
  title: string;
  component: "integration-category";
  _uid: string;
  [k: string]: any;
}

export interface IntegrationGridStoryblok {
  component: "integration-grid";
  _uid: string;
  [k: string]: any;
}

export interface IntegrationLinkStoryblok {
  title: string;
  url: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "integration-link";
  _uid: string;
  [k: string]: any;
}

export interface IntegrationListStoryblok {
  items?: (ISbStoryData<ContentIntegrationStoryblok> | string)[];
  component: "integration-list";
  _uid: string;
  [k: string]: any;
}

export interface IntegrationPlatformStoryblok {
  type?: "" | "zapier" | "integratly" | "pabbly";
  url?: string;
  component: "integration-platform";
  _uid: string;
  [k: string]: any;
}

export interface IntegrationUseCaseStoryblok {
  title: string;
  component: "integration-use-case";
  _uid: string;
  [k: string]: any;
}

export interface LoginFeaturesStoryblok {
  subtitle: string;
  title: string;
  content: string;
  link_title?: string;
  link?: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  background_image?: AssetStoryblok;
  component: "login-features";
  _uid: string;
  [k: string]: any;
}

export interface LoginInfoStoryblok {
  features?: LoginFeaturesStoryblok[];
  component: "login-info";
  _uid: string;
  [k: string]: any;
}

export interface MainMenuColumnStoryblok {
  title?: string;
  column_items?: (MainMenuColumnItemIconStoryblok | MainMenuColumnItemImageStoryblok)[];
  style: "" | "primary_icons" | "secondary_icons" | "horizontal_images";
  component: "main-menu-column";
  _uid: string;
  [k: string]: any;
}

export interface MainMenuColumnItemIconStoryblok {
  icon?: number | string;
  title: string;
  subtitle?: string;
  link?: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  has_translated_page?: boolean;
  component: "main-menu-column-item-icon";
  _uid: string;
  [k: string]: any;
}

export interface MainMenuColumnItemImageStoryblok {
  image?: AssetStoryblok;
  title: string;
  subtitle: string;
  link?: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "main-menu-column-item-image";
  _uid: string;
  [k: string]: any;
}

export interface MainMenuContentStoryblok {
  image?: AssetStoryblok;
  title: string;
  subtitle: string;
  show_link?: boolean;
  link_text?: string;
  load_demo?: boolean;
  link?: Exclude<MultilinkStoryblok, {linktype?: "email"}>;
  component: "main-menu-content";
  _uid: string;
  [k: string]: any;
}

export interface MainMenuItemStoryblok {
  label: string;
  url?: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  is_horizontal_images?: boolean;
  columns?: MainMenuColumnStoryblok[];
  menu_content?: MainMenuContentStoryblok[];
  component: "main-menu-item";
  _uid: string;
  [k: string]: any;
}

export interface MenuColumnStoryblok {
  title?: string;
  links?: MenuLinkStoryblok[];
  component: "menu-column";
  _uid: string;
  [k: string]: any;
}

export interface MenuLinkStoryblok {
  link: Exclude<MultilinkStoryblok, {linktype?: "asset"}>;
  label: string;
  has_translated_pages?: boolean;
  component: "menu-link";
  _uid: string;
  [k: string]: any;
}

export interface MetatagsStoryblok {
  title?: string;
  description?: string;
  og_title?: string;
  component: "metatags";
  _uid: string;
  [k: string]: any;
}

export interface PricingOverviewStoryblok {
  title?: string;
  tier: "" | "starter" | "business" | "premium";
  component: "pricing-overview";
  _uid: string;
  [k: string]: any;
}

export interface PrivacyItemStoryblok {
  title: string;
  description: RichtextStoryblok;
  component: "privacy-item";
  _uid: string;
  [k: string]: any;
}

export interface PromoCardStoryblok {
  image?: AssetStoryblok;
  title?: string;
  subtitle?: string;
  cta_text?: string;
  button_color?: string;
  background_color?: string;
  border_color?: string;
  cta_link?: Exclude<MultilinkStoryblok, {linktype?: "email"}>;
  component: "PromoCard";
  _uid: string;
  [k: string]: any;
}

export interface RedirectConfigStoryblok {
  redirect_entries?: RedirectEntryStoryblok[];
  component: "redirect-config";
  _uid: string;
  [k: string]: any;
}

export interface RedirectEntryStoryblok {
  source_url: string;
  target: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "redirect-entry";
  _uid: string;
  [k: string]: any;
}

export interface ResourceCardsStoryblok {
  items?: ResourceCardsItemStoryblok[];
  component: "resource-cards";
  _uid: string;
  [k: string]: any;
}

export interface ResourceCardsItemStoryblok {
  badge_text?: string;
  image: AssetStoryblok;
  subtitle?: string;
  title?: string;
  link?: Exclude<MultilinkStoryblok, {linktype?: "email"}>;
  component: "resource-cards-item";
  _uid: string;
  [k: string]: any;
}

export interface ResourceGridStoryblok {
  component: "resource-grid";
  _uid: string;
  [k: string]: any;
}

export interface SectionHeaderStoryblok {
  show_badge?: boolean;
  badge_text?: string;
  heading?: RichtextStoryblok;
  subheading?: RichtextStoryblok;
  align?: "" | "left" | "left-with-padding" | "center";
  theme?: "" | "light" | "dark";
  content?: (ContentButtonStoryblok | ContentLinkStoryblok | ContentTextStoryblok | ContentRichTextStoryblok)[];
  component: "section-header";
  _uid: string;
  [k: string]: any;
}

export interface SignupInfoStoryblok {
  signup_title: string;
  signup_subtitle: string;
  title_left: string;
  content_left: RichtextStoryblok;
  background_image?: AssetStoryblok;
  login?: any;
  left_content?: any;
  privacy_content?: any;
  privacy_resume: PrivacyItemStoryblok[];
  component: "signup-info";
  _uid: string;
  [k: string]: any;
}

export interface SocialIconLinkStoryblok {
  title?: string;
  with_link?: boolean;
  url?: string;
  component: "social-icon-link";
  _uid: string;
  [k: string]: any;
}

export interface TemplatesGridStoryblok {
  component: "templates-grid";
  _uid: string;
  [k: string]: any;
}

export interface TestimonialItemStoryblok {
  comment: string;
  score: string;
  name: string;
  job_title?: string;
  provider: "" | "trustpilot" | "capterra" | "product_hunt" | "getapp";
  resume_text?: string;
  component: "testimonial-item";
  _uid: string;
  [k: string]: any;
}

export interface TestimonialsStoryblok {
  items?: TestimonialItemStoryblok[];
  component: "testimonials";
  _uid: string;
  [k: string]: any;
}

export interface UniqueTestimonialStoryblok {
  title?: string;
  name?: string;
  job_title?: string;
  component: "unique-testimonial";
  _uid: string;
  [k: string]: any;
}

export interface VideoGridStoryblok {
  component: "video-grid";
  _uid: string;
  [k: string]: any;
}

export interface WistiaVideoStoryblok {
  video_id: string;
  image?: AssetStoryblok;
  component: "wistia-video";
  _uid: string;
  [k: string]: any;
}
